version: '3.7'

services:
  app:
    container_name: server
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./config_docker/Dockerfile
    entrypoint: [ "/home/app/config_docker/entrypoint.sh" ]
    volumes:
      - static_volume:/home/app/static
      - media_volume:/home/app/media
    expose:
      - 8000
    env_file:
      - .env

  nginx:
    container_name: nginx
    restart: always
    image: nginx:1.23-alpine
    ports:
      - 80:80
    volumes:
      - ./config_docker/nginx_default.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/home/app/static
      - media_volume:/home/app/media

volumes:
  static_volume: {}
  media_volume: {}
  # post/res_data: {}